-- UPDATED: 14/10/2025 --- Remove old settings
-- require("nvim-treesitter.configs").setup({
--     highlight = {
--         enable = true,
--         additional_vim_regex_highlighting = false,
--     },
--     incremental_selection = {
--         enable = true,
--     },
--     indent = {
--         enable = true
--     },
--     autotag = {
--         enable = true,
--     }
-- })
